---
sidebar: sidebar 
permalink: get-started/prerequisites.html 
keywords: what are bluexp operational resiliency requirements, economic efficiency prerequisites 
summary: Comece a usar o serviço de resiliência operacional da BlueXP  verificando o suporte para seu ambiente, acesso à rede, login e navegador da Web. 
---
= Pré-requisitos de resiliência operacional do BlueXP 
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Comece verificando a prontidão do seu ambiente operacional, login, acesso à rede e navegador da Web.

Para usar o serviço de resiliência operacional, você deve garantir que seu ambiente atenda a todos os requisitos.

* Seu ambiente deve atender a todos os requisitos do BlueXP , incluindo um login e acesso à rede a partir de um navegador da Web.
+
Consulte a https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-standard-mode.html["Início rápido do BlueXP "^] e https://docs.netapp.com/us-en/bluexp-setup-admin/reference-networking-saas-console.html["Informações de rede do BlueXP "^]a .

* O serviço exige que todos os clusters sejam monitorados pelo consultor digital, o que requer o AutoSupport habilitado no ativo. Consulte a https://docs.netapp.com/us-en/active-iq/index.html["Documentação do Digital Advisor"^].
* Você precisa ter credenciais de acesso aos clusters.
* Para correção automática, é necessário um conetor BlueXP . É útil se o BlueXP  Connector estiver ativo e ativado e o sistema ONTAP for descoberto antes de iniciar a correção usando a resiliência operacional do BlueXP . Se o conetor não estiver no lugar, o serviço de resiliência operacional orienta você por esses processos. Se, em vez disso, você corrigir usando um arquivo Ansible, o BlueXP  Connector não será necessário.

